server:
  port: 80
  
spring:
  application:
    name: book_springboot
  #datasource 설정  
  datasource: 
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
  #Failed to start bean 'documentationPluginsBootstrapper'; error
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail: 
    host: smtp.naver.com 
    port: 465
    username: phsk710@naver.com
    password: asd
    properties: 
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

#mybatis setting
mybatis:
  mapper-locations: mapper/*.xml
#  type-aliases-package: com.ssafy.enjoytrip.attraction.model, com.ssafy.enjoytrip.user.model
  type-aliases-package: com.ssafy.enjoytrip.*.model

 
# logging
logging:
  level: 
    root: info
    com.ssafy.enjoytrip: debug

    
